export const ADMIN_APPROPRODUIT_REQUEST = 'ADMIN_APPROPRODUIT_REQUEST'
export const ADMIN_APPROPRODUIT_SUCCESS = 'ADMIN_APPROPRODUIT_SUCCESS'
export const ADMIN_APPROPRODUIT_FAIL = 'ADMIN_APPROPRODUIT_FAIL'

export const ALL_APPROPRODUIT_REQUEST = 'ALL_APPROPRODUIT_REQUEST'
export const ALL_APPROPRODUIT_SUCCESS = 'ALL_APPROPRODUIT_SUCCESS'
export const ALL_APPROPRODUIT_FAIL = 'ALL_APPROPRODUIT_FAIL'

export const NEW_APPROPRODUIT_REQUEST = 'NEW_APPROPRODUIT_REQUEST'
export const NEW_APPROPRODUIT_SUCCESS = 'NEW_APPROPRODUIT_SUCCESS'
export const NEW_APPROPRODUIT_RESET = 'NEW_APPROPRODUIT_RESET'
export const NEW_APPROPRODUIT_FAIL = 'NEW_APPROPRODUIT_FAIL'

export const DELETE_APPROPRODUIT_REQUEST = 'DELETE_APPROPRODUIT_REQUEST'
export const DELETE_APPROPRODUIT_SUCCESS = 'DELETE_APPROPRODUIT_SUCCESS'
export const DELETE_APPROPRODUIT_RESET = 'DELETE_APPROPRODUIT_RESET'
export const DELETE_APPROPRODUIT_FAIL = 'DELETE_APPROPRODUIT_FAIL'

export const UPDATE_APPROPRODUIT_REQUEST = 'UPDATE_APPROPRODUIT_REQUEST'
export const UPDATE_APPROPRODUIT_SUCCESS = 'UPDATE_APPROPRODUIT_SUCCESS'
export const UPDATE_APPROPRODUIT_RESET = 'UPDATE_APPROPRODUIT_RESET'
export const UPDATE_APPROPRODUIT_FAIL = 'UPDATE_APPROPRODUIT_FAIL'

export const APPROPRODUIT_DETAILS_REQUEST = 'APPROPRODUIT_DETAILS_REQUEST'
export const APPROPRODUIT_DETAILS_SUCCESS = 'APPROPRODUIT_DETAILS_SUCCESS'
export const APPROPRODUIT_DETAILS_FAIL = 'APPROPRODUIT_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'