export const ADMIN_MACHINE_REQUEST = 'ADMIN_MACHINE_REQUEST'
export const ADMIN_MACHINE_SUCCESS = 'ADMIN_MACHINE_SUCCESS'
export const ADMIN_MACHINE_FAIL = 'ADMIN_MACHINE_FAIL'

export const ALL_MACHINE_REQUEST = 'ALL_MACHINE_REQUEST'
export const ALL_MACHINE_SUCCESS = 'ALL_MACHINE_SUCCESS'
export const ALL_MACHINE_FAIL = 'ALL_MACHINE_FAIL'

export const NEW_MACHINE_REQUEST = 'NEW_MACHINE_REQUEST'
export const NEW_MACHINE_SUCCESS = 'NEW_MACHINE_SUCCESS'
export const NEW_MACHINE_RESET = 'NEW_MACHINE_RESET'
export const NEW_MACHINE_FAIL = 'NEW_MACHINE_FAIL'

export const DELETE_MACHINE_REQUEST = 'DELETE_MACHINE_REQUEST'
export const DELETE_MACHINE_SUCCESS = 'DELETE_MACHINE_SUCCESS'
export const DELETE_MACHINE_RESET = 'DELETE_MACHINE_RESET'
export const DELETE_MACHINE_FAIL = 'DELETE_MACHINE_FAIL'

export const UPDATE_MACHINE_REQUEST = 'UPDATE_MACHINE_REQUEST'
export const UPDATE_MACHINE_SUCCESS = 'UPDATE_MACHINE_SUCCESS'
export const UPDATE_MACHINE_RESET = 'UPDATE_MACHINE_RESET'
export const UPDATE_MACHINE_FAIL = 'UPDATE_MACHINE_FAIL'

export const MACHINE_DETAILS_REQUEST = 'MACHINE_DETAILS_REQUEST'
export const MACHINE_DETAILS_SUCCESS = 'MACHINE_DETAILS_SUCCESS'
export const MACHINE_DETAILS_FAIL = 'MACHINE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'