export const ADMIN_MAINTENANCE_REQUEST = 'ADMIN_MAINTENANCE_REQUEST'
export const ADMIN_MAINTENANCE_SUCCESS = 'ADMIN_MAINTENANCE_SUCCESS'
export const ADMIN_MAINTENANCE_FAIL = 'ADMIN_MAINTENANCE_FAIL'

export const ALL_MAINTENANCE_REQUEST = 'ALL_MAINTENANCE_REQUEST'
export const ALL_MAINTENANCE_SUCCESS = 'ALL_MAINTENANCE_SUCCESS'
export const ALL_MAINTENANCE_FAIL = 'ALL_MAINTENANCE_FAIL'

export const NEW_MAINTENANCE_REQUEST = 'NEW_MAINTENANCE_REQUEST'
export const NEW_MAINTENANCE_SUCCESS = 'NEW_MAINTENANCE_SUCCESS'
export const NEW_MAINTENANCE_RESET = 'NEW_MAINTENANCE_RESET'
export const NEW_MAINTENANCE_FAIL = 'NEW_MAINTENANCE_FAIL'

export const DELETE_MAINTENANCE_REQUEST = 'DELETE_MAINTENANCE_REQUEST'
export const DELETE_MAINTENANCE_SUCCESS = 'DELETE_MAINTENANCE_SUCCESS'
export const DELETE_MAINTENANCE_RESET = 'DELETE_MAINTENANCE_RESET'
export const DELETE_MAINTENANCE_FAIL = 'DELETE_MAINTENANCE_FAIL'

export const UPDATE_MAINTENANCE_REQUEST = 'UPDATE_MAINTENANCE_REQUEST'
export const UPDATE_MAINTENANCE_SUCCESS = 'UPDATE_MAINTENANCE_SUCCESS'
export const UPDATE_MAINTENANCE_RESET = 'UPDATE_MAINTENANCE_RESET'
export const UPDATE_MAINTENANCE_FAIL = 'UPDATE_MAINTENANCE_FAIL'

export const MAINTENANCE_DETAILS_REQUEST = 'MAINTENANCE_DETAILS_REQUEST'
export const MAINTENANCE_DETAILS_SUCCESS = 'MAINTENANCE_DETAILS_SUCCESS'
export const MAINTENANCE_DETAILS_FAIL = 'MAINTENANCE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'