export const paiementsConstants = {

    ADMIN_PAIEMENT_REQUEST : 'ADMIN_PAIEMENT_REQUEST',
    ADMIN_PAIEMENT_SUCCESS : 'ADMIN_PAIEMENT_SUCCESS',
    ADMIN_PAIEMENT_FAIL : 'ADMIN_PAIEMENT_FAIL',

    ALL_PAIEMENTS_REQUEST : 'ALL_PAIEMENTS_REQUEST',
    ALL_PAIEMENTS_SUCCESS : 'ALL_PAIEMENTS_SUCCESS',
    ALL_PAIEMENTS_FAIL : 'ALL_PAIEMENTS_FAIL',

    NEW_PAIEMENT_REQUEST : 'NEW_PAIEMENT_REQUEST',
    NEW_PAIEMENT_SUCCESS : 'NEW_PAIEMENT_SUCCESS',
    NEW_PAIEMENT_RESET : 'NEW_PAIEMENT_RESET',
    NEW_PAIEMENT_FAIL : 'NEW_PAIEMENT_FAIL',

    DELETE_PAIEMENT_REQUEST : 'DELETE_PAIEMENT_REQUEST',
    DELETE_PAIEMENT_SUCCESS : 'DELETE_PAIEMENT_SUCCESS',
    DELETE_PAIEMENT_RESET : 'DELETE_PAIEMENT_RESET',
    DELETE_PAIEMENT_FAIL : 'DELETE_PAIEMENT_FAIL',

    UPDATE_PAIEMENT_REQUEST : 'UPDATE_PAIEMENT_REQUEST',
    UPDATE_PAIEMENT_SUCCESS : 'UPDATE_PAIEMENT_SUCCESS',
    UPDATE_PAIEMENT_RESET : 'UPDATE_PAIEMENT_RESET',
    UPDATE_PAIEMENT_FAIL : 'UPDATE_PAIEMENT_FAIL',

    PAIEMENT_DETAILS_REQUEST : 'PAIEMENT_DETAILS_REQUEST',
    PAIEMENT_DETAILS_SUCCESS : 'PAIEMENT_DETAILS_SUCCESS',
    PAIEMENT_DETAILS_FAIL : 'PAIEMENT_DETAILS_FAIL',

    CLEAR_ERRORS : 'CLEAR_ERRORS'
}