export const ADMIN_PAIEMENT_REQUEST = 'ADMIN_PAIEMENT_REQUEST'
export const ADMIN_PAIEMENT_SUCCESS = 'ADMIN_PAIEMENT_SUCCESS'
export const ADMIN_PAIEMENT_FAIL = 'ADMIN_PAIEMENT_FAIL'

export const ALL_PAIEMENT_REQUEST = 'ALL_PAIEMENT_REQUEST'
export const ALL_PAIEMENT_SUCCESS = 'ALL_PAIEMENT_SUCCESS'
export const ALL_PAIEMENT_FAIL = 'ALL_PAIEMENT_FAIL'

export const NEW_PAIEMENT_REQUEST = 'NEW_PAIEMENT_REQUEST'
export const NEW_PAIEMENT_SUCCESS = 'NEW_PAIEMENT_SUCCESS'
export const NEW_PAIEMENT_RESET = 'NEW_PAIEMENT_RESET'
export const NEW_PAIEMENT_FAIL = 'NEW_PAIEMENT_FAIL'

export const DELETE_PAIEMENT_REQUEST = 'DELETE_PAIEMENT_REQUEST'
export const DELETE_PAIEMENT_SUCCESS = 'DELETE_PAIEMENT_SUCCESS'
export const DELETE_PAIEMENT_RESET = 'DELETE_PAIEMENT_RESET'
export const DELETE_PAIEMENT_FAIL = 'DELETE_PAIEMENT_FAIL'

export const UPDATE_PAIEMENT_REQUEST = 'UPDATE_PAIEMENT_REQUEST'
export const UPDATE_PAIEMENT_SUCCESS = 'UPDATE_PAIEMENT_SUCCESS'
export const UPDATE_PAIEMENT_RESET = 'UPDATE_PAIEMENT_RESET'
export const UPDATE_PAIEMENT_FAIL = 'UPDATE_PAIEMENT_FAIL'

export const PAIEMENT_DETAILS_REQUEST = 'PAIEMENT_DETAILS_REQUEST'
export const PAIEMENT_DETAILS_SUCCESS = 'PAIEMENT_DETAILS_SUCCESS'
export const PAIEMENT_DETAILS_FAIL = 'PAIEMENT_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'