export const ADMIN_PROTOCOLEESSP_REQUEST = 'ADMIN_PROTOCOLEESSP_REQUEST'
export const ADMIN_PROTOCOLEESSP_SUCCESS = 'ADMIN_PROTOCOLEESSP_SUCCESS'
export const ADMIN_PROTOCOLEESSP_FAIL = 'ADMIN_PROTOCOLEESSP_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'